volumes:
  poke-db-data:
services:
  bakugan:
    build:
      context: ./api/bakugan
      dockerfile: Dockerfile

    image: bakugan
    volumes:
      - ./api/bakugan:/usr/src/app
    ports:
      - 3000:3000

  poke:
    build:
      context: ./api/poke
      dockerfile: Dockerfile

    depends_on:
      - poke-db

    image: poke
    volumes:
      - ./api/poke:/app
    ports:
      - 5000:5000

  poke-db:
    image: mysql:8.0.33
    volumes:
      - poke-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poke
      MYSQL_USER: poke
      MYSQL_PASSWORD: poke

    ports:
      - 3306:3306

  wiki-frontend:
    build:
      context: ./wiki-frontend
      dockerfile: Dockerfile

    image: wiki-frontend
    volumes:
      - ./wiki-frontend:/usr/share/nginx/html
    ports:
      - 8080:80
