FROM nginx:1.27.1-alpine

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/
#COPY ./styles /usr/share/nginx/html/
#COPY ./js /usr/share/nginx/html/
#COPY ./public /usr/share/nginx/html/
#COPY ./tailwind.config.js /usr/share/nginx/html/
